# Set data and user input location
input_land_use_path: 'C:\Users\bnichols\Documents\soundcast_landuse_scenario_builder\example\lu_allocation_inputs\land_use\2050'
input_pums_data_path: 'C:\Users\bnichols\Documents\soundcast_landuse_scenario_builder\example\lu_allocation_inputs\pums_data'
input_gis_data_path: 'C:\Users\bnichols\Documents\soundcast_landuse_scenario_builder\example\lu_allocation_inputs\gis_data.gdb'

# File names. Most likely, these will remain unchanged. 
seed_hh_file: 'seed_households.csv'
seed_person_file: 'seed_persons.csv'
parcel_file: 'parcels_urbansim.txt'
synthetic_pop_file: 'hh_and_persons.h5'
puma_layer: 'pumas_2010'
taz_layer: 'study_area_taz'

# Output dir. This is where the inputs to populationsim will reside. 
# Warning- this entire directory will be over-written. 
output_dir: 'C:\Users\bnichols\Documents\soundcast_landuse_scenario_builder\example'

update_jobs: True
update_hh: True

taz_id: 'taz'
block_group_id: 'geoid10'
puma_id: 'pumace10'
parcel_id: 'parcelid'