# Set data and user input location
input_land_use_path: 'C:\Workspace\land_use_test\example\inputs\land_use'
input_pums_data_path: 'C:\Workspace\land_use_test\example\inputs\pums_data'
input_gis_data_path: 'C:\Workspace\land_use_test\example\inputs\gis_data.gdb'

# File names. Most likely, these will remain unchanged. 
seed_hh_file: 'seed_households.csv'
seed_person_file: 'seed_persons.csv'
parcel_file: 'parcels_urbansim.txt'
synthetic_pop_file: 'hh_and_persons.h5'
puma_layer: 'pumas_2010'
taz_layer: 'study_area_taz'

# Output dir. This is where the inputs to populationsim will reside. 
# Warning- this entire directory will be over-written. 
popsim_run_dir: 'C:/Workspace/land_use_test/example/populationsim_run_dir'

# Location of model run to update synthetic household/person and parcel data
model_dir: 'L:\vision2050\soundcast\dseis\integrated\final_runs\tod\tod_run_8.run_2018_10_29_15_01\2050'


# Soundcast run used to build target distributions as inputs for populationsim
land_use_path: 'R:\e2projects_two\SoundCast\Inputs\dev\landuse\2050\test_2050'

update_jobs: True
update_hh: True

taz_id: 'taz'
block_group_id: 'geoid10'
puma_id: 'pumace10'
parcel_id: 'parcelid'